echo 'data mining'
python3.4 knowledge_graph.py 'data mining'
echo 'computer graphics'
python3.4 knowledge_graph.py 'computer graphics'
echo 'computer vision'
python3.4 knowledge_graph.py 'computer vision'
echo 'database'
python3.4 knowledge_graph.py 'database'
echo 'deep learning'
python3.4 knowledge_graph.py 'deep learning'
echo 'high performances computing'
python3.4 knowledge_graph.py 'high performances computing'
echo 'machine learning'
python3.4 knowledge_graph.py 'machine learning'
echo 'networks'
python3.4 knowledge_graph.py 'networks'
echo 'social network'
python3.4 knowledge_graph.py 'social network'
echo 'software engineering'
python3.4 knowledge_graph.py 'software engineering'
